### ISSUE TITLE
Using jdk.incubator.vector leads to degraded performance

### ISSUE THREAD

**Issue by eustas** [eustas/2im#2]
- [ ] auto-unrolling  could be improved (see `EncoderSimd.sumAbs`); partial manual unrolling makes code faster
- [ ] manually unrolled loops **unexpectedly** gets worse from 2x to 4x
- [ ] vectorised version is slower than non-vectorized (see `EncoderSimd.updateGeGeneric`); reason: conversion not inlined and happens inside call to `jdk.incubator.vector.AbstractVector::convert`

**Comment by eustas** [comment]
@PaulSandoz Hi! I've filed an issue to OpenJDK about problems with `jdk.incubator.vector`, but perhaps it is stuck in moderation process. That is why I'm trying to reach you directly.
Long story short - using vector API makes calculations slower, not faster. In one case I've succeeded by manually unrolling (one-line) loop. In the other case `convert(VectorOperators.F2I, 0)` works unbelievably slow.
Could provide more details on reproduction of the problems, if you are interested.
Thanks in advance.

**Comment by PaulSandoz** [comment]
@eustas the quickest approach is to email [panama-dev](https://mail.openjdk.java.net/mailman/listinfo/panama-dev) (if you don't join the email it will require moderation, but CC me, and i can reply quicker), presenting code examples showing the problem, preferably using JMH.

You may be encountering a regression that was recently identified, see https://mail.openjdk.java.net/pipermail/panama-dev/2021-March/012355.html, in other cases it may be the method has yet to be optimized.
